name: Test Emby Patch (Minimal)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check VM startup
      run: |
        echo "VM started: $(date)"
        uname -a
        whoami  # runner

    - name: Download DEB
      run: |
        wget https://github.com/MediaBrowser/Emby.Releases/releases/download/4.9.2.6/emby-server-deb_4.9.2.6_amd64.deb -O test.deb
        ls -lh test.deb || echo "Download failed"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-deb
        path: test.deb
